-- An external Stellar wallet is an authentication identity only. It never
-- replaces the separately managed JarvisPayz owner/agent/C-wallet stack.
alter table public.users alter column google_sub drop not null;
alter table public.users add column if not exists wallet_scope text;

-- Preserve every existing encryption scope exactly as it is. New wallet-only
-- accounts receive a random scope generated by the API rather than deriving
-- key-encryption material from a public wallet address.
update public.users set wallet_scope = google_sub where wallet_scope is null and google_sub is not null;
alter table public.users alter column wallet_scope set not null;
create unique index if not exists users_wallet_scope_key on public.users(wallet_scope);

create table if not exists public.stellar_identities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  public_key text not null unique,
  created_at timestamptz not null default now(),
  unique (user_id, public_key)
);

-- Challenges are persisted and consumed atomically, making a signed message
-- one-time use even when multiple API instances are running.
create table if not exists public.stellar_login_challenges (
  id uuid primary key,
  public_key text not null,
  purpose text not null check (purpose in ('login', 'link')),
  user_id uuid references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists stellar_login_challenges_expiry_idx on public.stellar_login_challenges(expires_at);

alter table public.stellar_identities enable row level security;
alter table public.stellar_login_challenges enable row level security;
revoke all on public.stellar_identities, public.stellar_login_challenges from anon, authenticated;
